#!/usr/bin/env python

import argparse
from mmagic.apis import MMagicInferencer

parser = argparse.ArgumentParser(
    prog="RunVideoInferer", description="Basic Python script to run inferer"
)

parser.add_argument("filename", help="input video file path")
parser.add_argument(
    "-o", "--output", required=True, help="path to generate output file at"
)


def get_editor():
    return MMagicInferencer(model_name="basicvsr_pp")


def main():
    args = parser.parse_args()
    editor = get_editor()
    results = editor.infer(video=args.filename, result_out_dir=args.output)
    print(results)


if __name__ == "__main__":
    main()
